# Generated by Django 5.1.1 on 2024-09-05 08:49

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ApartmentForRenting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", models.CharField(max_length=255)),
                ("size", models.PositiveIntegerField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=9)),
                ("view", models.CharField(max_length=255)),
                ("room_number", models.PositiveSmallIntegerField()),
                ("bathrooms", models.CharField(max_length=255)),
                ("cladding", models.CharField(max_length=255)),
                ("floor", models.PositiveSmallIntegerField()),
                ("renting_period", models.CharField(max_length=255)),
                ("phone_number", models.CharField(max_length=25)),
                ("is_sold", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="ApartmentForSelling",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", models.CharField(max_length=255)),
                ("size", models.PositiveIntegerField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=9)),
                ("view", models.CharField(max_length=255)),
                ("room_number", models.PositiveSmallIntegerField()),
                ("bathrooms", models.CharField(max_length=255)),
                ("cladding", models.CharField(max_length=255)),
                ("floor", models.PositiveSmallIntegerField()),
                ("property", models.CharField(max_length=255)),
                ("phone_number", models.CharField(max_length=25)),
                ("is_sold", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Land",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", models.CharField(max_length=255)),
                ("size", models.PositiveIntegerField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=9)),
                ("property", models.CharField(max_length=255)),
                ("phone_number", models.CharField(max_length=25)),
                ("is_sold", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="ShopForRenting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", models.CharField(max_length=255)),
                ("size", models.PositiveIntegerField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=9)),
                ("renting_period", models.CharField(max_length=255)),
                ("phone_number", models.CharField(max_length=25)),
                ("is_sold", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="ShopForSelling",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", models.CharField(max_length=255)),
                ("size", models.PositiveIntegerField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=9)),
                ("property", models.CharField(max_length=255)),
                ("phone_number", models.CharField(max_length=25)),
                ("is_sold", models.BooleanField(default=False)),
            ],
        ),
    ]
