# Generated by Django 5.1.1 on 2024-09-06 12:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("real_estate", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apartmentforrenting",
            name="price",
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name="apartmentforselling",
            name="price",
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name="land",
            name="price",
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name="shopforrenting",
            name="price",
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name="shopforselling",
            name="price",
            field=models.PositiveBigIntegerField(),
        ),
    ]
